### PR TITLE
Keyboard shortcuts

### PR DESCRIPTION
**Pull request by leonkunert**
preparing for #51

### CODE REVIEW

**Comment by leonkunert** [comment]
dependent on #47

**Comment by leonkunert** [comment]
Keyboard shortcuts for

-[x] Changing Classes (1-9)
-[x] Save (Space ç)
- [x] Skip (Tab)
- [x] Back (Shift + Tab)
- [x] Reset (Esc)

**Comment by leonkunert** [comment]
@tecoholic could you also review this?

**Comment by tecoholic** [comment]
@leonkunert Hi, thanks for the reminder. I will try to get it done in a couple of days.

**Comment by tecoholic** [comment]
@leonkunert I resolved the conflicts in the PR and tested this locally.

1. The 1-9 keys doesn't seem to be working as expected. I added `console.log()` statements to the `ClassesBlock.vue`'s `keypress` function. It doesn't seem to log anything. I think this might be due to the `stopPropogation` [in the annotation page](https://github.com/tecoholic/ner-annotator/pull/52/files#diff-3443dc145151e15db29c536b71aa9e016c61e8c8d4191ce6ad289c192bfc416eR110).  To resolve this, we should probably limit have all the keyboard shortcut logic in a single logic, especially since we have a `stopPropogation` call.
2. The Tab and Shift Tab keys for moving forward and back seems to be a poor choice for a UI with so many buttons, as hitting Tab cycles through all the buttons on the interface. Choosing the arrow keys would be a better choice IMHO
3. This entire feature should also be made a app setting that can be enabled or disabled based on user's preferences. Otherwise, hitting a random key might produce surprising results for the user, which could be confusing. I can take care of this if you wish.

I have also invited you to be a collaborator in the project :) Feel free to move the commits over a new branch in this repo or create new branches :)

**Comment by leonkunert** [comment]
@tecoholic Can you check this again. 
Using arrows for forward and back. 
Simplified 1-9 for classes and added an option in the sidebar.

**Comment by tecoholic** [comment]
@leonkunert Sure thing. I will test and merge this, if everything is alright. :)

**Review by alvi-khan — APPROVED** [review]

**Pull request merged**
