### PR TITLE
Migrate from webpack to Vite & upgrade Tauri to V2

### PR DESCRIPTION
**Pull request by kurt-mueller-osumc**
This pull requests updates dependencies as well as migrates from Webpack to ViteJS.

### CODE REVIEW

**Comment by tecoholic** [comment]
@kurt-mueller-osumc Dear lord! Did you actually manage to pull this off? This is amazing. I have tried and given up at least 3 times. I have approved the CI run. Let's see if everything passes. :crossed_fingers:

**Comment by tecoholic** [comment]
@kurt-mueller-osumc Thank you. I would also try to get a local build working and test the desktop version this week to verify everything is working. This is truly amazing work.

**Comment by kurt-mueller-osumc** [comment]
> However, the interface was broken and there are plenty of warnings in the terminal as well. So I am worried things might be broken.

When you say the interface, are you talking about javascript assets or image assets?

I've been using the latest version of yarn and node v21.

**Comment by tecoholic** [comment]
@kurt-mueller-osumc Hi, it took longer than expected for me to come back to this project. While things are generally okay build wise, I am seeing a bunch of UI issues. I think I might need to upgrade the UI library and make other changes. Can you kindly enable "Allow edits from maintainers" on this PR so I can push the changes to this PR and merge once I have everything working?

**Comment by tecoholic** [comment]
Okay. I have tested that this build works and have tagged it as "pre-release" I am merging this to the master branch.

**Review by tecoholic — APPROVED** [review]

**Comment by EverybodyKurts** [comment]
Awesome. Sounds great :).

**Comment by EverybodyKurts** [comment]
Glad I could play a part in updating this project. Thanks for taking the time to review it, fix it up, and merge it.

**Comment by kurt-mueller-osumc** [comment]
I'm glad to have played a part in updating this project. Thanks for taking the time to review it, fix it up, and merge it.

**Comment by tecoholic** [comment]
@kurt-mueller-osumc Thanks a lot for doing most of the grunt work. I have tried and failed multiple times to do this and the software wouldn't have seen this update for quite a while.

**Pull request merged**
