### PR TITLE
Bug fixes

### LINKED ISSUE #58: It is possible to add tags with no text.

### PR DESCRIPTION
**Pull request by alvi-khan**
Fixes #58, #59 and #60.

For #59, the tagging progress indicator on the left sidebar remains incomplete on the last sentence. Left this as is on purpose since saving or skipping on the last sentence leaves the user on that sentence. Leaving it up to @tecoholic to decide how they want to handle the UX for that.

### CODE REVIEW

**Comment by tecoholic** [comment]
@alvi-khan Wow. Thank you for taking the time to identify and fix the bugs. I will try to review them this weekend and get them merged.

**Comment by tecoholic** [comment]
@alvi-khan I cannot pull your changes to my local machine for testing. And your repo's URL https://github.com/alvi-khan/ner-annotator returns a 404. Do you by any chance have the repo marked private?

**Comment by alvi-khan** [comment]
@tecoholic Sorry about that. I've been having some synchronization issues with my local repo. Could you check again please when you have the time?

**Comment by tecoholic** [comment]
@alvi-khan Thanks for getting this sorted out. I will review and merge the PRs when I get some free time this week.

**Comment by alvi-khan** [comment]
Added fix for #65.

**Comment by alvi-khan** [comment]
@tecoholic please add a proxy approval here as well. TIA.

**Review by tecoholic — APPROVED** [review]
Adding proxy review for @alvi-khan to merge changes

**Comment by alvi-khan** [comment]
Addressed in #70.

**Pull request closed without merging**
