### PR TITLE
Added option to open a new file.

### PR DESCRIPTION
**Pull request by alvi-khan**
Addresses #63.

### CODE REVIEW

**Comment by tecoholic** [comment]
@alvi-khan Hi, Thank you for the PR. I will try to review this in the weekend and create a new release if I can merge this.

**Comment by alvi-khan** [comment]
**Description**:

Added an 'Import' option under the 'Annotations' tab. The option can be used to import previously exported annotations. This will allow users to continue working on a file they have partially annotated.

image

Once the imported annotations are restored, the labelled tokens in each of the sentences (including the current one) are updated.

image

**Review by tecoholic — APPROVED** [review]
Add proxy approval for @alvi-khan

**Comment by alvi-khan** [comment]
Addressed in #72.

**Pull request closed without merging**
